### ISSUE TITLE
Update to Livewire v2

### ISSUE THREAD

**Issue by jonassiewertsen** [jonassiewertsen/statamic-livewire#1]

**Comment by jsblair9** [comment]
haha was just about to open this issue... actually meant to do it last night, aka the exact time you did!

I may need to do this asap, happy to PR if it helps

**Comment by jonassiewertsen** [comment]
A PR would be appreciated a lot 😊

**Comment by gofish543** [comment]
During the upgrade to Livewire 2, would it be beneficial to bring in Laravel 8.0 support?

**Comment by jonassiewertsen** [comment]
@gofish543 Laravel 8 Support would be great 🥳

I did open a separate issue for it: 
https://github.com/jonassiewertsen/statamic-livewire/issues/3

**Comment by rickmills** [comment]
Possibly best to do these individually. Whilst Livewire 2 is good to go and compatible with Laravel 7 it might be a bit longer for Statamic to get Laravel 8 support.

**Comment by jonassiewertsen** [comment]
I agree 💯  @rickmills. That's why they have been split up in two separate issues so we can tackle them separately 😎

**Comment by jonassiewertsen** [comment]
The update is there. 

https://github.com/jonassiewertsen/statamic-livewire/commit/30ea8d6da0226d63602343026b0896b68c0396b2
