### ISSUE TITLE
Computed Properties

### ISSUE THREAD

**Issue by aerni** [jonassiewertsen/statamic-livewire#11]
Is there a way to use computed properties with Antlers? https://laravel-livewire.com/docs/2.x/properties#computed-properties

**Comment by jonassiewertsen** [comment]
I haven't tried it with Antlers yet 🤷‍♂️

Does it simply not work? Are you getting any error message?

**Comment by aerni** [comment]
In Blade you would access a computed property like this `{{ $this->post->title }}`. There's no way to access `$this` in Antlers.

**Comment by mkriegeskorte** [comment]
I’ve solved it by explicitly passing the data in the render method like this:

```
public function render()
{
  return view('livewire.template', [
    'property' => $this->property,
  ]);
}
```

**Comment by jonassiewertsen** [comment]
Computed properties are not supported at the moment. 

Hopefully the workaround from @mkriegeskorte does help.

**Comment by sheldonkotyk** [comment]
Just wanted to note here that the workaround [here](https://github.com/jonassiewertsen/statamic-livewire/issues/11#issuecomment-1129788540) works in Livewire 3.

**Comment by marcorieser** [comment]
> Just wanted to note here that the workaround [here](https://github.com/jonassiewertsen/statamic-livewire/issues/11#issuecomment-1129788540) works in Livewire 3.



> Just wanted to note here that the workaround [here](https://github.com/jonassiewertsen/statamic-livewire/issues/11#issuecomment-1129788540) works in Livewire 3.

Are computed properties in v3 not accessable like normal properties? Wondering if the workaround is needed.

**Comment by sheldonkotyk** [comment]
> Are computed properties in v3 not accessable like normal properties? Wondering if the workaround is needed.

[They still require the $this->propertyname. ](https://livewire.laravel.com/docs/computed-properties#basic-usage)

**Comment by marcorieser** [comment]
> > Are computed properties in v3 not accessable like normal properties? Wondering if the workaround is needed.
> 
> [They still require the $this->propertyname. ](https://livewire.laravel.com/docs/computed-properties#basic-usage)
> 
> ```
> Must use $this in your template
> 
> Unlike normal properties, computed properties aren't directly available inside your component's template. Instead, you must access them on the $this object. For example, a computed property named posts() must be accessed via $this->posts inside your template.
> ```

You are right.

**Comment by aerni** [comment]
You could probably use Antlers' PHP functionality to make it work like `{{? $this->property ?}}`.

**Comment by marcorieser** [comment]
> You could probably use Antlers' PHP functionality to make it work like `{{? $this->property ?}}`.

FYI: Seems like `$this` refers to Antlers `NodeProcessor`.

`Call to undefined method Statamic\View\Antlers\Language\Runtime\NodeProcessor::posts()`
