### ISSUE TITLE
Unable to cache blade views due to this package

### ISSUE THREAD

**Issue by gofish543** [jonassiewertsen/statamic-livewire#2]
Could you add a resources/views/.gitkeep to the repository so that the view:cache command can still work?

![Screen Shot 2020-09-11 at 2 03 04 PM](https://user-images.githubusercontent.com/10394554/92963085-85007600-f437-11ea-8487-af3a662e2038.png)

**Comment by jonassiewertsen** [comment]
Sorry for the late answer. I did miss this issue somehow until today. 

I will look into it.
