### ISSUE TITLE
model.defer in antler templates

### ISSUE THREAD

**Issue by mkriegeskorte** [jonassiewertsen/statamic-livewire#22]
Hi!

I’m trying to bind a deferred model to an input in an antlers template like that:

```html
<input type="text" wire:model.defer="searchTerm" />
```

Unfortunately this doesn’t work at all. Using it without `defer` runs like expected.

Does someone has a suggestion what might be wrong?

Thank you :)

**Comment by jonassiewertsen** [comment]
We'll be working on a V3 version. Please reopen the ticket or respond here, if the issue still appears in V3.
