### ISSUE TITLE
Mounted parameters get augmented

### ISSUE THREAD

**Issue by FR6** [jonassiewertsen/statamic-livewire#25]
Is this the desired effect that when passing an `Statamic\Entries\Entry` parameter it gets augmented?

On [vendor/jonassiewertsen/statamic-livewire/src/Tags/Livewire.php](https://github.com/jonassiewertsen/statamic-livewire/blob/master/src/Tags/Livewire.php#L43):
`$parameters->toArray()` will convert the `Entry` to an augmented array.
If we replace `->toArray()` with `->all()` the Entry stays an object.

![image](https://user-images.githubusercontent.com/286685/203893836-53a87917-67bb-4d5d-a479-ae103d0ea0ae.png)

Here is the output from Ray from line #43:

![image](https://user-images.githubusercontent.com/286685/203893902-25d834ad-309a-456b-bfcc-0fcbf1833eb4.png)

Let me know if it's a bug and you want me to PR.

**Comment by jonassiewertsen** [comment]
This is indeed by purpose, as this was the only way it did work without problems at the time of the addon creation. Which has been a while ago. 

Your statement is correct, that parameters will be passed as an array. What is the bug? What is the problem with this approach? Is there any trouble you running into?

If can take another look, if you can provide more context, as I don't think to understand the problem correctly.

**Comment by FR6** [comment]
Ok no problem, I was just curious if it was really what was expected.

Thank you!
