### ISSUE TITLE
Duplicate synthesizer keys?

### ISSUE THREAD

**Issue by adevade** [jonassiewertsen/statamic-livewire#40]
I was scanning through the code and noticed that both synths uses the same `$key`. Don't know if this matters?

https://github.com/jonassiewertsen/statamic-livewire/blob/9e5a4edbcc6c553c220e177dde42dc7b8d734a4b/src/Synthesizers/EntrySynthesizer.php#L9-L11

https://github.com/jonassiewertsen/statamic-livewire/blob/9e5a4edbcc6c553c220e177dde42dc7b8d734a4b/src/Synthesizers/EntryCollectionSynthesizer.php#L9-L11

**Comment by jonassiewertsen** [comment]
You're right. 

That's fixed now.
