### ISSUE TITLE
Dispatching events returns "Could not find Livewire component in DOM tree"

### ISSUE THREAD

**Issue by taylorcammack** [jonassiewertsen/statamic-livewire#43]
Updating a template that worked in Livewire V2.

Have an Antlers template that contains a button that dispatches an event to a modal component further down the page

```antlers
<button @click="$wire.$dispatchTo('modal-default', 'show', '{{ id }}')">
  View Summary
</button>
```
Dispatches to...

```antlers
{{ livewire:modal-default view="incentives" }}
```

Which returns: 
`Uncaught Could not find Livewire component in DOM tree` 

I know the modal is rendering on the page, because if I set the `show` property to it in the Livewire class, it will render. Something just seems screwy when trying to dispatch to it.

Any ideas?

**Comment by marcorieser** [comment]
My first approach would be to render everything via blade and have a look if it works. Maybe its a bug in Livewire itself.

**Comment by taylorcammack** [comment]
Thanks and yup, appears to be a Livewire bug
