### ISSUE TITLE
Customizing the progress bar

### ISSUE THREAD

**Issue by ineptian** [jonassiewertsen/statamic-livewire#46]
I have updated the config according to [this](https://livewire.laravel.com/docs/navigate#customizing-the-progress-bar), but my progress bar just remains blue. Does this work for anyone else?

**Comment by jonassiewertsen** [comment]
This seems more like a support question.

I would recommend asking on Discord.

**Comment by marcorieser** [comment]
@ineptian should work with the newest Livewire version.

**Comment by jonassiewertsen** [comment]
I had a look with @robdekort today and the livewire:navigate seems to be in a pretty early stage. 

https://github.com/livewire/livewire/discussions/7011

This feature should be included with version 3.0.6, but it does not feel stable at the moment.
https://github.com/livewire/livewire/releases/tag/v3.0.6

No doubt though, that it will be in a short amount of time :-)

**Comment by jonassiewertsen** [comment]
This overview might help:
https://github.com/livewire/livewire/discussions?discussions_q=is%3Aopen+navigate

**Comment by marcorieser** [comment]
Funny, seemed to had no issues when using it (wire:navigate and the changed color) last Monday but will check again tomorrow.
