### ISSUE TITLE
Livewire 3 / statamic-livewire 3 Error

### ISSUE THREAD

**Issue by bretvanhorn** [jonassiewertsen/statamic-livewire#47]
Hi-

I am getting an error I am having trouble resolving when I have Statamic Livewire installed. It has worked well until we upgraded Statamic to 4 and Livewire to 3, now the entire front end of the site will not load and displays the attached error. 

If I uninstall Statamic Livewire, the error goes away. Strangely, I think I have commented out all the Antlers Livewire calls and it is still throwing this error. Any guidance will be welcome and please let me know if you need more informaiton. See screenshots for error and versions of everything. 

Thanks!

<img width="1502" alt="Screenshot 2023-10-17 at 1 51 19 PM" src="https://github.com/jonassiewertsen/statamic-livewire/assets/13129372/3408df44-158a-46bd-8024-e4a4555b0d58">
<img width="1116" alt="Screenshot 2023-10-17 at 1 51 41 PM" src="https://github.com/jonassiewertsen/statamic-livewire/assets/13129372/f3016e91-80ac-49ab-8d09-07d3d54bd8bb">

**Comment by jonassiewertsen** [comment]
Can you show the complete trace?

Is any class of the addon included?

Did you use the experimental feature?
https://github.com/jonassiewertsen/statamic-livewire/#experimental-statamic-support

It seems that Livewire tries to synthesize a null value, which does not work. Maybe a problem with your properties?

https://livewire.laravel.com/docs/properties

**Comment by marcorieser** [comment]
Not sure if this helps but in v2 I created dynamic properties on the fly in the `mount()` method and was binding them in the template. In v3 this threw some errors (not sure if the same as here) but I had to switch from:
```php
class MyComponent extends ... {
public function mount() {
  foreach(PropertyProvider::all() as $property {
    $this->$property = '';
  }
}
```
to:
```php
class MyComponent extends ... {
public $form;
public function mount() {
  foreach(PropertyProvider::all() as $property {
    $this->form[$property] = '';
  }
}
```

**Comment by bretvanhorn** [comment]
@jonassiewertsen and @marcorieser Thank you for your responses and suggestions. At this time, I am pretty sure this is on my end and has more to do with property types, etc. You can close this ticket for now and if for some reason I find it's not on my end, I'll let you know. But I am pretty sure it's all me. :-)
