### ISSUE TITLE
Select value not changing on frontend

### ISSUE THREAD

**Issue by nmdgent-jefverme** [jonassiewertsen/statamic-livewire#48]
Hi

I have an issue with the value of my select not updating on the frontend.

![image](https://github.com/jonassiewertsen/statamic-livewire/assets/16621102/90e9e342-f15c-482e-b337-55ebf55b2ea9)

**Expected behaviour** 
I Have two dropdowns with options to filter jobs (a statamic collection). One where you can select a location, one where you can select a campus. When a user changes the location dropdown, I want the campus select to reset to the default "Select" value.

**Actual behaviour**
When a value is selected in the campus dropdown and a user changes the location dropdown, the value in my livewire component for campus resets to "", the URL parameter is removed, but the option stays selected on the frontend.

These are the properties
![image](https://github.com/jonassiewertsen/statamic-livewire/assets/16621102/80dc3d15-689d-4098-9980-4cf4a923e659)

This is how my selects are created in my antler template: 
![image](https://github.com/jonassiewertsen/statamic-livewire/assets/16621102/3aadeee3-e807-42f4-b438-0589dfef3803)

This is how I reset my component value
![image](https://github.com/jonassiewertsen/statamic-livewire/assets/16621102/c8147640-72e5-4159-b76b-174211d5b409)

Anyone has any idea what's going on here?

**Comment by nmdgent-jefverme** [comment]
Tiny update: I've added the following code purely for fixing the visual issue of the selected option not updating: 
![image](https://github.com/jonassiewertsen/statamic-livewire/assets/16621102/ca8cfb31-6d0e-4510-824f-7800da1ac8ee)

**Comment by marcorieser** [comment]
So its resolved now?

**Comment by jonassiewertsen** [comment]
I think this is resolved and might be a Livewire issue, not connected to the addon directly. 

Please let me know if I am wrong.
