### ISSUE TITLE
Everything breaks in v.3 Upgrade ?

### ISSUE THREAD

**Issue by yabdab** [jonassiewertsen/statamic-livewire#49]
Just upgraded to Statamic 4.49.0 and Livewire 3.0 and now all my components are  unable to be found ( Livewire \ Exceptions \ ComponentNotFoundException ).

Tried clearing cache and all the usual stuff, but nothing worked. 

Only resolution was to step back down to 2.12.0 and everything worked again.

Are there any steps that need to be done when going from LW2 -> LW3 ?

Thanks.

**Comment by marcorieser** [comment]
Have you stepped trough the upgrade guide?
https://livewire.laravel.com/docs/upgrading

**Comment by yabdab** [comment]
Thanks for the quick reply guys!

Went through the guide and now everything works again 🎉

**Comment by robdekort** [comment]
Nice

**Comment by jonassiewertsen** [comment]
I added a little node in the Readme to help upgrading in the future:

https://github.com/jonassiewertsen/statamic-livewire/blob/master/README.md#upgrade

Let me know if we can adjust ist, to help even more
