### ISSUE TITLE
The ivewire component not being detected in production environment

### ISSUE THREAD

**Issue by spazacomm** [jonassiewertsen/statamic-livewire#54]
The livewire component is not being loaded in production environment. Everything works fine in local. in production I notice when I view the page source, the livewire scripts aren't loaded. I am running this in azure web app

**Comment by jonassiewertsen** [comment]
Can you help by giving me more context?

`php please support:details` would help. 

I would guess, without any further information, that it's related to caching.

**Comment by jonassiewertsen** [comment]
Closing as I am waiting for information.
