### ISSUE TITLE
FR: Support `Values` and `Value` objects

### ISSUE THREAD

**Issue by edalzell** [jonassiewertsen/statamic-livewire#58]
Almost everything in Statamic, after augmentation, is a `Values` or `Value` object. It would be amazing if this addon had synths for those.

I quickly tried to write them and ran into a weird error, I'll see if I can figure it out and PR it.

**Comment by jonassiewertsen** [comment]
What do you think @edalzell ?

https://github.com/jonassiewertsen/statamic-livewire/pull/62
