### ISSUE TITLE
Undocumented step required when using livewire:scriptConfig tag

### ISSUE THREAD

**Issue by godismyjudge95** [jonassiewertsen/statamic-livewire#59]
Found out the hard way that if you need to compile the Livewire assets separately (ie. to add an Alpine plugin) there is one additional step required.

I had assumed that by using the `{{ livewire:scriptConfig }}` tag the livewire forms script would be included.  However that appears to only set up some preliminary config variables.

I was able to get the forms working again by adding the following to by `site.js`:
```js
import { Livewire, Alpine } from "../../vendor/livewire/livewire/dist/livewire.esm";
import "../../vendor/aerni/livewire-forms/resources/dist/js/livewire-forms";

window.Alpine = Alpine;
Livewire.start();
```

**Comment by marcorieser** [comment]
@godismyjudge95 The Readme already tells you to bundle the scripts yourself by pointing to the Livewire docs:
https://github.com/jonassiewertsen/statamic-livewire/blob/master/README.md#L35

But maybe that's not clear enough. Could you open a PR with the desired changes?

**Comment by jonassiewertsen** [comment]
Thanks for the information, I think that others might feel the same.

So I am looking forward to your PR as well.

**Comment by godismyjudge95** [comment]
I'm so sorry, I posted this on the wrong repo 😅 
I meant to post it on the Livewire Forms repo:  https://github.com/aerni/statamic-livewire-forms
