### ISSUE TITLE
419 Page Expired

### ISSUE THREAD

**Issue by aerni** [jonassiewertsen/statamic-livewire#63]
I've just deployed a website that uses v3.4.0, and I'm running into Livewire's infamous `419 Page Expired` issue when full static caching is on. It looks like PR https://github.com/jonassiewertsen/statamic-livewire/pull/61 might have some unforeseen side effects. I didn't run into this issue when testing the new replacer feature locally with Herd. I'll look into this and try to fix it.

**Comment by aerni** [comment]
Okay, so it turns out that Herd doesn't include Valet's Statamic driver that takes care of full static caching. So it would always run PHP instead of only loading the static HTML, which is why I didn't catch the 419 locally. Now I run into the same issue locally and can debug 💪

**Comment by marcorieser** [comment]
@aerni how have you enabled the Statamic driver in Herd?

**Comment by aerni** [comment]
Add [this driver](https://github.com/laravel/valet/blob/master/cli/Valet/Drivers/Specific/StatamicValetDriver.php) by following [these instructions](https://herd.laravel.com/docs/1/extending-herd/custom-drivers).

**Comment by aerni** [comment]
Alright, so the `419` is triggered because I'm accessing `this.$wire` before the `STATAMIC_CSRF_TOKEN` placeholder is replaced with the current CSRF token. I'll have to find a workaround for that issue on my end.

However, this is a separate issue to full static caching not working correctly with the current implementation of the `AssetsReplacer`. I'll figure out a different approach to make it work with both half and full measure static caching.

**Comment by marcorieser** [comment]
> Add [this driver](https://github.com/laravel/valet/blob/master/cli/Valet/Drivers/Specific/StatamicValetDriver.php) by following [these instructions](https://herd.laravel.com/docs/1/extending-herd/custom-drivers).

Thanks. I reported an issue on the Herd repo which gets fixed in next release. Shouldn't be needed then.
https://github.com/beyondcode/herd-community/issues/812
