### ISSUE TITLE
Page fields content is missing

### ISSUE THREAD

**Issue by wm-simon** [jonassiewertsen/statamic-livewire#65]
Hey, my current site has multiple page fields, which I show inside the livewire component. The component is an item filter for collection entries. When I load the site for the first time, all contents are shown correctly, but when I filter for entries, the page fields are not shown anymore.

**Comment by marcorieser** [comment]
@jonassiewertsen discussing that directly in discord with wm-simon.

**Comment by marcorieser** [comment]
The issue was, that Livewire loses context about the cascade on subsequent requests. Solved it by passing the data into livewire.
