### ISSUE TITLE
Replace {{ links }} in Antlers with custom pagination 

### ISSUE THREAD

**Issue by Rbiggunz** [jonassiewertsen/statamic-livewire#67]
Hello folks.
I am trying to replace standard pagination links  {{ links }}:

        <ul>
            {{ cars }}
                <li>{{ current_price }} EUR || {{ title }}</li>
            {{ /cars }}
        </ul>
        
        {{ links }}
        
        to custom:
        {{ if paginate.last_page > 1}}
            {{ partial:if_exists src="partials/pagination/custom_pagination" paginate=cars }}
        {{ /if }}
        
        or even more simple:
         {{ partial:if_exists src="partials/pagination/custom_pagination" paginate=cars }}
         
         but it does not work.
         
         Is it possible at all to achieve this?

**Comment by marcorieser** [comment]
Closing this for now.
